### PR TITLE
Memory Plugin

### PR DESCRIPTION
**Pull request by chrislaskey**
Hey there!

I recently wrote a FooTable plugin and thought others might find it useful. 

The plugin is called Memory and saves the table state in a cookie and restores the state when the page is reloaded.

It supports the common FooTable features like:
- Pagination
- Sorting
- Filtering
- Row Expansion

And it is compatible with multiple FooTable instances on a page, and with JavaScript libraries that use hash-based URLs like AngularJS and Ember.

Since it uses cookies for data storage, it adds a dependency on jQuery Cookie (https://github.com/carhartl/jquery-cookie).

The idea came from the Bookmarkable plugin by @akf (Amy Farrell).

### CODE REVIEW

**Comment by bradvin** [comment]
hey @chrislaskey 

This looks great - thanks so much for contributing this add-on for FooTable. 

Please check out the build errors : https://travis-ci.org/bradvin/FooTable/builds/31558661
Seems to be a missing semicolon according to the jshint rules.

As soon as it is building in travis I will merge this pull request.

**Comment by chrislaskey** [comment]
Hey @bradvin,

Thanks for the quick reply and kind words.

I've added the missing semi-colon and the build appears to be passing now. Apologies for not catching it before making the pull request.

Glad to help contribute to a great project!

**Comment by bradvin** [comment]
Would be a cool idea if you stored the state in localstorage (if available) and used cookies as a fallback

**Comment by chrislaskey** [comment]
Great suggestion! I just pushed an update with localStorage as the default and $.cookie as the fallback to my fork. Can I re-open this pull request and post the commits, or do I have to create a new pull request?

**Comment by bradvin** [comment]
awesome - it will have to be a new pull request

**Pull request merged**
