### PR TITLE
LESS version and CSS adjustments

### PR DESCRIPTION
**Pull request by felipefialho**
Adding LESS version for default style and improved
the complexity of the cascade in CSS.

Notify me any problem.

I hope it will be useful.

PS. Congratulations for this project, simply wonderful.

### CODE REVIEW

**Comment by felipefialho** [comment]
Yes, I sent a version of LESS and CSS generated.

I'm learning to use Git, so there came the changes for you. =p

**Comment by bradvin** [comment]
cool - don't worry it took me a while to get this whole GIT collaboration process too :)

I will test the changes asap and merge it in

thanks again for contributing back to FooTable

**Comment by seriema** [comment]
@bradvin if you accept this merge for LESS I can integrate a LESS build task to GruntJS and even add it to `grunt watch` so it builds CSS continuously as you update the LESS files. =)

**Comment by bradvin** [comment]
I would like to add LESS to the V2 branch. 

@LFeh would you be willing to do this for the V2 branch, as there are too many merge conflicts with this PR now.

@seriema after it is added to the V2 branch I would like to do what you suggest and integrate it into the build

**Comment by seriema** [comment]
@bradvin cool. I could even prepare a PR so it's just to grab it once you've got the LESS files. Since this is an old PR, I could do LESS support too if there's no response.

**Comment by bradvin** [comment]
@seriema sounds good

**Comment by felipefialho** [comment]
@bradvin I make or the @seriema going make this adjustment?

**Comment by bradvin** [comment]
@LFeh  If you could that would be great, as you did the original LESS files for footable. Please could you do them in the V2 branch - thanks

**Comment by felipefialho** [comment]
Ok, I going make and push... I try make today.

**Comment by seriema** [comment]
I was just going to do the GruntJS integration, but ended up doing the LESS as well =/ almost done with that now...

**Comment by felipefialho** [comment]
@seriema Are you going send a Less version with GruntJS integration?

**Comment by seriema** [comment]
Yeah, I'll have it done within the hour. But there are things that could be done better with it. Especially some selectors could be removed I think, it's a tad too specific atm.

**Comment by seriema** [comment]
@LFeh You can find my PR [here](https://github.com/bradvin/FooTable/pull/89) now. I could use some help in leveraging LESS even more, with variables and mixins. Are you up for it? Otherwise I could do it this weekend.

**Comment by felipefialho** [comment]
@seriema Could you make it this weekend? 

I'll be busy this week, if you do get will be great. ;D

**Comment by felipefialho** [comment]
@seriema This is my Grunt Boilerplate: https://github.com/LFeh/Grunt-Base

**Comment by seriema** [comment]
@LFeh yeah I think I can.

Cool, feel free to update the Gruntfile.js in V2 branch =)

**Pull request closed without merging**
