### PR TITLE
Support for html form input fields and dynamic column content

### PR DESCRIPTION
**Pull request by minroo**
To overcome issues 194 & 156. Switches/moves content between row-detail and detail-show. It includes the demo/documentation. Added a data attribute data-editable, it achieves by using a mapping variable and moving data between the row-detail and detail-show. By default it creates the map for any cell which has form input elements.

### CODE REVIEW

**Comment by bradvin** [comment]
thanks for contributing this @minroo !!

**Comment by claudchan** [comment]
The field will disappear on windows resize. Is there any fix on this?

Source: http://stackoverflow.com/questions/22710776/text-input-not-working-properly-on-mobile-with-footable

Here the issue produce example:
http://jsfiddle.net/claudchan/L3gxmvdh/

How to re-produce this issue:
1. resize to mobile view. Click "Run" again.
2. click expand any row, make edit any price value.
3. resize the windows rapidly.
4. You will see the TD is disappear and lost.

**Comment by steveush** [comment]
Hi,

We are no longer supporting V2, if you look at this repo V3 is the latest version of the plugin and allows for HTML fields and it has a base for editing.

Thanks

**Comment by claudchan** [comment]
Hi,
Thanks. There is a fix by JimBacon: https://github.com/fooplugins/FooTable/pull/390/commits/1fb72ab01687d3b680a5577eb10cbbfd817c8eef

Can you merge this commit? I understand you have no longer support. Hope any fooTable member can merge this into master.

**Comment by steveush** [comment]
Hi,

I'm actually on the verge of deleting the V2 branch and performing a clean up of the issues and pull requests so we have a clean slate as it were for working on V3. I'll chat to my dev partner about possibly keeping the V2 branch and then just simply merging all the pull requests but I'm not sure of the outcome, personally I am for dropping the whole V2 branch as it is only causing us more headaches going forward.

Thanks

**Comment by jeffconklin** [comment]
Good thought, Steve. Sorry to go off topic here, but if you are no longer developing V2, I would also add that it would be great if your company would also clean up all the demos / pages / sites that you mange to point to V3. The GitHub page points to http://fooplugins.com/plugins/footable-jquery/, which is a download for V2. And I know a few people that have searched for Footable, are brought to http://fooplugins.com/footable-demos, and have developed based on those pages (even if they downloaded v3 from here). Rather confusing. A cleanup here and everywhere to mark V2 and it's documentation deprecated would be great.

**Comment by minroo** [comment]
Footable starting from version 3 has full support. Can you elaborate which
version you are using, etc?

**Comment by steveush** [comment]
Hey Jeff,

Thanks for pointing that out, I've changed the GitHub page link (didn't even notice at the top there) and I'll see what I can get done cleaning up the old V2 docs to point to the new V3 documentation, I may just end up doing a permanent redirect of http://fooplugins.com/footable-demos to the new docs here on GitHub,

Thanks

**Pull request merged**
