### PR TITLE
Travis config fix

### PR DESCRIPTION
**Pull request by seriema**
This should fix Travis-CI. It was missing the config file telling Travis that this is a NodeJS project, so it wasn't running `npm install` and `npm test` like expected.

### CODE REVIEW

**Comment by seriema** [comment]
Wait, forgot that Travis-CI [doesn't have GruntJS installed globally](https://github.com/travis-ci/travis-ci/issues/1064). Fixing. Wait with merging until there's a green checkbox saying "OK to merge".

**Comment by seriema** [comment]
Gah! @bradvin  wait! haha Wait until the green checkbox is showing

**Comment by seriema** [comment]
@dboune yes, I missed that because regular jshint didn't have any issues with it but grunt-contrib-jshint had. I've fixed that and working on the jshint config file again since it's obvioulsy different between regular jshint and grunt-contrib-jshint.

**Comment by dboune** [comment]
Cool. The space change isn't so important, but it was worth mentioning anyway. Interesting to know that npm does that.

Glad that you caught the JSON issue. It is an unfortunate thing, and I often find myself mildly annoyed by that lacking in the spec.

**Pull request merged**
