### PR TITLE
Added ability to override the toggler with other HTML markup.

### PR DESCRIPTION
**Pull request by akf**
Hello again, 

This is potentially more controversial than my last pull request. :-) The change is small, but I may very well be missing an easier or more idiomatic way of achieving my goal. Hopefully the demo explains how to use it; here's why I'm proposing this: 

The goal is to enable customization of the toggle control beyond what can be accomplished with CSS. We've been using FooTable 0.5, with the default plus and minus background images. I was asked to add text for accessibility. (I haven't actually seen how screen readers handle FooTables, but I'm reading between the lines that it's possible to have columns hidden in that scenario, and that the expand/contract option became unavailable). 

This is the solution I came up with. It's a pretty limited change to footable.js that does leave a lot to the imagination for the web developer. In the demo, I use the old plus/minus images, but what we're probably going to use in production is an icon (font) with "Show Details"/"Hide Details" text in a span that is visually hidden but available to screen readers. 

By the way, I started poking at this a couple of weeks ago on the 0.5 release. I found the V2 code cleaner and easier to follow -- nice work! 

Thanks for taking a look.

### CODE REVIEW

**Comment by elioscordo** [comment]
Hi,
felt the same problem and still I am not happy with this automatic toggler.
Could you provide more info on this?

thanks,
elio

**Comment by bradvin** [comment]
@akf thanks for this Amy - I thought it was done very neatly

**Comment by bradvin** [comment]
@elioscordo what do you not like about the automattic toggler? Do you want to disable it altogether?

**Comment by akf** [comment]
Thanks, @bradvin!

@elioscordo -- I'm guessing at your question, but ... the idea here was that you can build your own toggler; the one in the demo is just an example.

**Comment by elioscordo** [comment]
thanks for the response,
ok then it would be enough to address how to do in the doc... I personally felt like discovering how to do it by my own...  
hey guys thanks a lot!! the plugin is really useful!
hugs

**Pull request merged**
