### PR TITLE
Reorganize's project structure in order to ease the integration process 

### PR DESCRIPTION
**Pull request by Nerian**
Hi Bradvin,

Awesome project! I love that you are using data attributes to semantically add behaviour to HTML structures. I think this is a very good start and I have no doubts that once more plugins appear this is going to replace Datatables in many projects :)

I am going to use Footable for a new project and I am going to be using Ruby on Rails. In RoR we usually package our assets, like FooTable, in Gems. This makes installing and updating assets something very seamless and pretty much automatic. I will be packaging FooTable in a gem at [this repo](https://github.com/Nerian/FooTable-rails).

Rails expects things to be organized in a specific way. A convention. This pull request structures your assets following that convention. It would be awesome if you could merge these changes, since this will save me countless hours each time I want to update the Gem with your code changes :sweat_smile:

I changed the url of assets in the demo HTML files to point to the new locations of said assets. The icons url doesn't match, because I set the url to be relative from the 'assets' folder. We can fix that if you use [Jekyll](https://github.com/mojombo/jekyll) to build these pages.

Let me know what you think.

Thanks!

### CODE REVIEW

**Comment by bradvin** [comment]
looks good Nerian. Does the RoR convention require the css folder to be "stylesheets" and the js folder to be "javascripts"? I would prefer to keep those as "css" and "js"

Also - how do I rename files in Git? I have not figured it out yet, and I want to rename the main footable js file to not have a version number in the filename

thanks!

**Comment by Nerian** [comment]
Yes, RoR expects it to be `stylesheets` and `javascripts`. But automating a change of a folder name on my side should be an easy thing to do.

I just moved the files normally. Git figured it out that contents didn't change, just the location and that gets interpreted as a rename of files.

Detailed answer:
http://stackoverflow.com/questions/2641146/handling-file-renames-in-git#comment2656031_2641146

Thanks!

**Comment by bradvin** [comment]
Hey Nerian,

pls check the footable.css image paths as they do not seem right:

background: url('assets/images/plus.png') no-repeat 5px center;

should rather be

background: url('../../assets/images/plus.png') no-repeat 5px center;

**Comment by Nerian** [comment]
Done :)

**Comment by Nerian** [comment]
Hi, is there anything else that needs to be changed?

**Comment by steveush** [comment]
Hi Nerian,

I wasn't around when this was first done so not sure what Brad intends to do. I'm going to assign it across to him and try chat with him tomorrow.

Thanks
Steve

**Comment by bradvin** [comment]
Hey Nerian,

The one thing holding me back from doing this is the css image paths that turn into something like this:

background: url('../../assets/images/plus.png')

I think it is messy. The images are only used in the CSS, so I feel they should be in an images folder inside the CSS folder.

Your thoughts on this?

**Comment by Nerian** [comment]
Hi,

Rails just expects images to be in that folder, so then you don't need to specify the full path, just the name of the image. Example image attached.

assets

But I am OK if you want to put them in a folder inside the css directory. I can just automate moving the folder to the right location.

**Comment by Nerian** [comment]
Any feedback on this?

**Comment by Shinrai** [comment]
All the CSS files are extremely small. Why not just make sure they are compressed as much as they can be and then base64 encode them and use a data url?
such as url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEgAAAAYCAYAAABZY7uwAAAGPElEQVRYR+2Ya0wUVxTHz+zOPnFZHgFBpFioVl6VthASCD5CqjEg/WBiKIWmCR9qamKrjTUxbQbTxsSa0NbEkH4xTU0XYvhS0A+mGlFjTIS2CLpYLRSKCEJ4rCv73p2es3Zwl2Vn74AxfuhNbnZn5t4z9/7mf+8953Dwf5ElwIU+LSoqKpmde/yry+02L4ebXqezJSbEv9Pb29u9nP4r6KPFvqux8iuwEdrVhxePsHrCAPE8L+QWvNnk83ohIAYUvUvFqYDXaGDg9h9NPp/vaKzOLS0t1Tdu3Gix2Wxr5dqazeYHZWVlH+/du7czWjuLxfLp5OTksbm5OUOs97I8T0hIcKamph6pq6v7LgwQdm4qLCoRPO55UC9+EsOyXwTQ6uKgv7eb4DTFGkhDQ8PDM2fOpMdqR8+x7SNsmxalLXft2rWfKyoq3isvLwf8yMBxCgf/n2FRFAE/Lly/fh3QZivafD8CUMGmYsHncYDf52UZ+0IbNa8BXmuE27d6mADV1NSInZ3PRKHT6UCv1wftuVwucLvdC7Z37doFHR0d0WbNXb161bJ58+bagwcPgt/vB5VKpWjsUuNAIABqtRqam5sBbbahzboIQPlvvC34vS4QA7QM2Qun4kGt0cOdvt+WBUjuTayADh8+DDTJlSiI4B4/fjw6oLzCt4SAD7+e6GenQy05Nah4HVj7f2cGNDQ0FJyQXKEBZ2dnMynohQDKzS8SQET1LAMQcDwM3OllBjQ4OAhePBDkigY3/pycnJcH0Ma8TYKKQ5mCslNMBBWefCq4a73FBAiXjTgyMgIej0cWkFarhaysLMD9KuYe9EIUtCG3UOBxj1Mr3Of8yNOH9d5APzOg0dFRJkCZmZkvD6D1GwsELRLiFZ7zPjznPUjo/t3bzIDGxsaYAGVkZMgC6urqsmzdurX2eSoIbbahzchTLGdDnqDX8qAhGSkoXoTj8vhg8J6VGdDExETYcb7U6+j4T0tLkwV0+fJly7Zt214MoOz1eYJRrwGtRq0AD/rkXj84XF4Yus8GqLq6WpyammIClJKSAufOnYu6B126dMlSWVlZe+jQoeCpuBI/iPqeOHEC0GYb2oxU0LqcjYIpTgc6rUYRILfHC/Z5NwwP3mVSEAGamZlhApSUlCQLSFIQOYrk6K0EEDma5ChGBZSV/bpgNhlAr6P4j7243B6w2Z0wMvQnMyCMw4Jes1wh7xrjMVlAFy9etNTX19fSkn0ehZZ0a2trGy7bSAVlrlsvJJpXgUGvDJDT5YFZ2xMYHb7PDMhutzMBMplMsoAuXLhgyc/Pr5XgUExF3jRV+k+FlEXLj65JYaEOqtRGUh5dW63Wtu3bt0cCWpv1mpCcaAKj4WlcxFocThdMz9rhwchfzIDm5+eZAMXFxcVUUG5ubi0FmqGTXAyir68v+BxhRixDui/FcRKgHTt2RAJak5ktpCQnQJxRGaB5hwumpufg4egQE6CqqiqRAlKn0yn7DQwGA9BJdv78+aibNCmIANHESCkSqFAlkWIIED0vKCgIqkuK2yQFSf3pPilo586dkYDS174qpKYkwiqjstTKE4cTJqdmYfzB30yAaJMmR5GlkKMoc4rBqVOnvty9e7eAk1ZLS0cKWKXfxfelpSbBoXFI0FBN/vb29qP79u37KiKaT8tYJxjwmDfHm1jGvtDG9tgOTjzmJ8aGmQF1d4cnHkkpVEJTHXRdUlIiCwibJGHNw7pURpHDif5YXFz8SuiEenp6/kGwH+K9p5tUeKFUhhXrTASg1WuyhGhkkpNpHADT0zNR4T16OMIECGMx782bN/nQ1ITRaAzadTgcC/bpC5eWlvoxH7ScdKoWveuPcPl9i65CmGOHLoZ/YGDgAKY2fsCXRQ0IwwClp6cfcHvFZl6j7ASTZuPzekCn4T4bHx9vjiU/dOp+OXv2bA2mSWWbYvoT9uzZ04HO27uxbC56rrly5crnhYWFX+CSWXJDxWXn6u/v/3rLli3fYN8l0wqLFaTGuOcTjJHiFQ4m2Bz7Psa+3+PfmMmkkydP6nCAH6CCMuTehQoawwn+tH///mcpRrbBxZ8+ffoI9k8kRUqVupJSpUrLqLGx8Rj+2pcyu7zkLdsAX5ZWsea41B60MPZ/AVbCQFV5kuUNAAAAAElFTkSuQmCC)

device sprite from the WP plugin BTW.

**Pull request closed without merging**
