### PR TITLE
Implement a view button in addition to the current edit and delete buttons

### PR DESCRIPTION
**Pull request by bucketpress**
There are instances where we want to show detailed row info that does not need to be edited. And we want a button to trigger a view and is different from the edit button.

### CODE REVIEW

**Comment by steveush** [comment]
Hi,

I've merged all your pull requests, in future could you try keep all commits for a single feature to one pull request? Would make it easier to test and merge :) As for your changes, before I rebuild and include them into the next version I'll add in some options to control the visibility of these buttons so people can choose what to show from the defaults. Something along the lines of:

allowNew - Whether or not to show the Add Row button
allowView - Whether or not to show the View Row button
allowEdit - Whether or not to show the Edit Row button
allowDelete - Whether or not to show the Delete Row button

These will most likely just add classes to the table element to hide the various buttons but I will also make it control the column width as needed. This will also allow me to set the default visibility of the "View" button to be hidden so people that have implemented the editor don't all of a sudden have a new button that doesn't do anything in there tables ;)

Thanks for the commits.

**Comment by bucketpress** [comment]
Hi Steve,

First and foremost, sorry for the multiple commits. I haven't made much 
commits on github until now. I'll try to figure out how to do so as 
you've mentioned. As I didn't have 'write' capablity to your repo, it 
created a new branch for each file edit when I made the edits. Is there 
a better process? - for e.g. every time, create a new fork from your 
repo, make all the changes on this fork, and then stage all the files 
that were edited, then make a single commit?

By the way, if I'm not wrong - currently as long as we do not declare 
the editing options for delete, edit, view and add (e.g. editRow: 
function(row), then they are simply not shown. So with these 'allow's, 
does that mean that:
- if allowNew is true (default = false) && editRow: function(row) is 
  declared, then the button will be shown?

OR
- if allowNew is true BUT ediRow is not declared, then the button will 
  still be shown, just that nothing happens when it is clicked.

Anyway, I have another question: I'm trying to create checkboxes on 
every row in a column, with a 'master' checkbox to toggle the checkboxes 
of all rows that are currently shown on the table's page (i.e all rows 
that are currently in dom). Can I do these simply by inserting them as 
html data for each tbody row? and for the table's th, do likewise?

Will footable be able to filter the rows as :selected and not:selected?

Thanks!
Kevin

**Comment by steveush** [comment]
Hi,

At the moment the buttons will be shown regardless of whether or not the functions are supplied through the options. They simply did nothing when clicked so the new options allow for you to control the visibility of each.

As for the checkbox column there's a bit more to it to get it working looking at what you are wanting. I'll see if I can put together a generic checkbox column as a new column type that will integrate into the filtering, sorting and paging components.

Thanks for the suggestions

**Comment by bucketpress** [comment]
@steveush , I've managed to insert checkboxes and filter them, and i created a new issue #503 to document it.

**Comment by hfishere** [comment]
Thanks @steveush  for adding new options value, but i didnt still get the allowNew options work? Am i wrong?

**Comment by steveush** [comment]
Hi @hfishere,

The options are actually allowAdd, allowEdit, allowDelete and allowView. They are listed on the [editing component page](http://fooplugins.github.io/FooTable/docs/components/editing.html) and are available in the latest version of the plugin.

Thanks

**Comment by hfishere** [comment]
> Something along the lines of:
> 
> allowNew - Whether or not to show the Add Row button 
> allowView - Whether or not to show the View Row button
> allowEdit - Whether or not to show the Edit Row button
> allowDelete - Whether or not to show the Delete Row button

Oh man im just focused on this comment, lol. It should allowAdd right? And now it works. Thanks @steveush . Love this plugin. :+1:

**Pull request merged**
