### PR TITLE
LESS basics

### PR DESCRIPTION
**Pull request by seriema**
Added LESS support in GruntJS and "LESSified" the stylesheets. Also created a concatenated file called `footable.all.css` as well as `.min` versions of all CSS, as that's easily done in the GruntJS build task.

Just run `grunt less` if you want to just generate CSS, or use `grunt` to do everything. You can also run `grunt watch` and it will generate development (non-min) versions of CSS on the fly when you update a LESS file.

### CODE REVIEW

**Comment by seriema** [comment]
I recommend you rename `footable.less` to `footable.core.less` so that `footable.css` can be the "full version" as it's commonly done in a lot of projects.

Also, I feel that the focus on these different themes aren't really what I want FooTable for. I just want the responsivness. I had to strip out all the styling to use it in my project. A core file should just handle the responsivness, then you can have .theme files as a bonus. But functionality should be clearly separated from styling.

**Comment by seriema** [comment]
The LESS files can be done better, with usage of variables and mixins. If no one's doing it I could do it, but I'd like to focus on the JSHint issues now, if @bradvin has updated V2 branch?

**Comment by seriema** [comment]
@LFeh asked if I could update the LESS, so I'll do some more updates on this tomorrow morning. Expect an update in about 12h. I'll be doing some light refactoring of color values etc.

@bradvin , after that I'd like you to take a look at the selectors. Currently it'll quickly lead to specificity wars for people wanting to override a style. I could give you pointers on what to change and how, but I prefer you do it.

**Comment by bradvin** [comment]
@seriema I agree with renaming footable.less to footable.core.less, so that you just need to include a single file for all your footable css

**Comment by seriema** [comment]
OK I'll fix that. I should be done with this tonight.

**Comment by seriema** [comment]
OK that's enough for this PR!

I took the liberty of adding a CSSLint tool, but it's turned off from the test-task because of [a bug with CSSLint and media-queries with font-face in them](https://github.com/gruntjs/grunt-contrib-csslint/issues/12). To run the linter, just run `grunt csslint` but preferably after you've done `grunt less`. As with the JSHint, there's a config file (`.csslintrc`) and you should try to flip them on one at a time and fixing the issues. One rule is what I've commented on already and it's overly specific selectors (a good practice is not to include element).

@bradvin If you're happy with this, please merge it and update the V2 branch so I can fix the JSHint issues.

**Comment by felipefialho** [comment]
Very nice @seriema! :D

**Comment by bradvin** [comment]
@seriema great work - thanks :D

**Pull request merged**
