### PR TITLE
Reset .jshintrc file to pass jshint

### PR DESCRIPTION
**Pull request by seriema**
Currently FooTable was failing it's JSHint settings. A good way to get compliant is starting with a config that allows the current code to pass as-is. Then you start flipping the settings one by one and changing the code to be compliant. It's like paying off your credit-cards, you start with the worst one and take one at a time. :)

This PR configures JSHint to pass the code as-is. You should start by flipping the first flags, that start with `-W`, as they're so agreed upon within the JS community that they don't have regular named option flags.

### CODE REVIEW

**Comment by seriema** [comment]
I have a smaller .jshintrc to push but the connection is blocked where I am atm.

**Comment by seriema** [comment]
Hmm Travis is not configured, I thought that was done. I'll make a separate PR for Travis-CI integration.

**Comment by bradvin** [comment]
@seriema any idea what is going on with the build? https://travis-ci.org/bradvin/FooTable/builds/7830527

**Comment by bradvin** [comment]
@seriema and thanks for your help with this :)

**Comment by seriema** [comment]
@bradvin Thanks! Travis is not configured, so it's not doing the right things and that's why it's failing. I'll send a PR tonight after work. It's an easy fix. _famous last words_

I'd be happy to start solving some of the simpler JSHint issues once that's done, if you want? It will touch a lot of code but will just be a character change here and there, so let's be careful with conflicts in case you're working on the files without public pushes.

**Comment by bradvin** [comment]
@seriema cool that would be awesome if you could help out - I am busy with some changes on V2 branch so let me know and when you want to start on it and I can commit everything I have done

**Comment by seriema** [comment]
@bradvin I couldn't hold myself, sent some PR's =) Sadly this reset didn't work with Grunts version of jshint, since it doesn't allow specific warnings to be suppressed. Check my other PR's.

I will work on JSHint issues tonight though, in about 7h. If you could push everything until then it would be great.

**Comment by seriema** [comment]
[This PR](https://github.com/bradvin/FooTable/pull/87) fixes Travis-CI bugging out as it was doing in your link above, but it doesn't pass the build because of JSHint errors - at least it's now behaving correctly!

**Pull request merged**
