### PR TITLE
Adding 'forceResize' parameter to 'ft.resize()' method - defaults to: false

### PR DESCRIPTION
**Pull request by 6eDesign**
@Bravdin, 

I thought of a less intrusive way to force the ft.resize() method (AKA redraw) that we were talking about this week.  It works with the column picker plugin.  If this works for you, go ahead and merge it in.  Did you want me to submit a pull request for the column picker or would that be better hosted in its own repository?  I figured, either way, I'd wait until we have the force redraw issue figured out.

### CODE REVIEW

**Comment by 6eDesign** [comment]
I noticed it wasn't quite working with this 'travis' thing so I updated it a bit with strict equals comparisons for Travis.  Also, wanted to say, I had a look around some of your latest changes to FooTable and they look like they're all for the better, nice work!

**Comment by bradvin** [comment]
thanks for sending this through, but I had already catered for this. I was just busy testing everything before I commit, as it ended up being quite a big change. 

I ended up moving all the 'redraw' logic into it's own redraw function.
I also then added a new trigger so that this function can be trigger.
And then I trigger the redraw from within the resize function if all the conditions are met.

The reason for this was mainly so that you can trigger the redraw from a page (ie. outside of the plugin or extensions)

But regarding your column picker extension : I would like to include that as an extension, so please can you test it with my redraw changes and then submit a pull request for that.

I also want to look at using your json table builder as another extension

**Comment by bradvin** [comment]
check out https://github.com/bradvin/FooTable/commit/c38b445795647089255cf70a50dc570a9d38dd84

You can now do

$('table').trigger('footable_redraw');

**Comment by 6eDesign** [comment]
@bradvin 

No worries, I will check to see if triggering this new action will work with the Column-picker plugin.  I can get back to you soon.  About the column picker extension: that's no problem if you'd like to include it over here - that was the general idea: to contribute back to FooTable.  

The JSONTable, however, might be better served as a separate project - mostly because it is designed to be library agnostic (98%, but will soon be 100%).  Also, it works with or without FooTable (by disabling the makeFootable parameter).  Either way, I am still pursuing several avenues of active development for that project but I'm sure we could talk more in the future when I have all the loose ends completed.  Perhaps I could release and maintain a FooTable specific branch for your users and you could link over to my repo.  

Either way, I'll get back to you about the Columnpicker.

**Comment by 6eDesign** [comment]
_PS_  I checked out the latest version and $(ft.table).trigger('footable_redraw') is working perfectly for the column picker.  Thanks for adding this.

**Comment by 6eDesign** [comment]
_PS #2_  There seems to be some major restructuring going on with FooTable.  I have included the new css and javascript in the project and have encountered some issues with the pagination in particular.  On line 78 of the footable.paginate.js file, you have: 

```
 var $nav = $(ft.table).find(ft.pageInfo.pageNavigation);
```

But according to your docs, the pagination div can go anywhere so we should probably have 

```
 var $nav = $(ft.pageInfo.pageNavigation); // which fixes pagination when placed outside of the table
```

Unfortunately, this does little to fix the CSS which is also narrowed down to ".footable tfoot .pagination ul" (& similar).  It seems like you'd need to add a class to whichever div's match the provided selector and then narrow down the pagination CSS like that - or, _of course_, you could specify that the user should provide a specific class name for the pagination div.  

I like a lot of the changes you've been making but this one will break a lot of my (and perhaps others' as well) legacy code.  I really do applaud all of your efforts though, it looks like you've made some great progress.

**Comment by bradvin** [comment]
@6eDesign I have just checked in a whole number of fixes/changes/enhancements - check out the demos, especially the API demo on calling FooTable functions from outside.

WRT pagination : the paging control can go anywhere. I first try and find it within the table control. And then if I get nothing back I do a general check like you suggest.

I only wanted to style the paging control if it was inside the table. If you put it outside, then it is up to you to style it how you like.

please check it out and send through a pull request for the column picker

**Pull request closed without merging**
